version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Packaging artifacts...
      - cd ..
      - mkdir -p artifacts
      - cp -r backend/* artifacts/
      - cp appspec.yml artifacts/
      - cp scripts/* artifacts/

artifacts:
  files:
    - artifacts/**/*
